# Generated by Django 4.0.2 on 2022-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auth_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
