# Generated by Django 4.0.2 on 2022-03-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
