# Generated by Django 4.0.2 on 2022-03-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='quantuty',
            new_name='quantity',
        ),
    ]
