# Generated by Django 4.0.2 on 2022-03-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_quantuty_orderplaced_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Maharashtra', 'Maharshta'), ('\tAndhra Pradesh', '\tAndhra Pradesh'), ('\tBihar', '\tBihar'), ('Chandigarh (UT)', 'Chandigarh (UT)'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('\tMeghalaya', 'Meghalaya'), ('\tPunjab', '\tPunjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('\tUttar Pradesh', '\tUttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=60),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('order placed', 'Order Placed'), ('\tOrder confirm', '\tOrder confirm'), ('Order Packed', 'Order Packed'), ('Order Dispatch', 'Order Dispatch'), ('Order Dilivered', 'Order Dilivered'), ('\tRejected', '\tRejected')], default='Order Placed', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=250),
        ),
    ]
